spring.cloud.stream:
  function:
    definition: modelService
  bindings:
    modelService-in-0:
      destination: ConsumerDomain
  kafka:
    bindings:
      modelService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9092